# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/05-Factories

# production
prod:
  logger:
    class:   sfNoLogger
    param:
      level:   err
      loggers: ~

#  storage: 
#    param: 
#      session_cookie_domain: .wikipixel.com

# testing
test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: "%SF_TEST_CACHE_DIR%/sessions"

  response:
    class: sfWebResponse
    param:
      send_http_headers: false

  mailer:
    param:
      delivery_strategy: none

# development
dev:
  mailer:
    param:
      delivery_strategy: realtime

# all
all:
  storage:
    class: sfSessionStorage
    param:
      session_name: wikipixel_op

  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true

  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true

  user:
    class: myUser
    param:
      timeout:         1800
      logging:         "%SF_LOGGING_ENABLED%"
      use_flash:       true
      default_culture: "%SF_DEFAULT_CULTURE%"
